export const ROUTES = {
  HOME: '/',
  ABOUT: '/about-us',
  OUR_TEAM: '/our-team',
  SITAARE: '/sitaare',
  PROJECTS: '/projects',
  HEALTHCARE: '/health-care',
  SUSTAINABLE_LIVELIHOOD: '/sustainable-livelihood',
  EDUCATION: '/education',
  NUTRITION: '/nutrition',
  HOUSE_OF_HAPPINESS: '/house-of-happiness',
  MILESTONES: '/milestones',
  SUCCESS_STORIES: '/success-stories',
  OUR_PARTNERS: '/our-partners',
  DONATE_FOR_CAUSE: '/donate-for-a-cause',
  GET_INVOLVED: '/get-involved',
  PARTNER_WITH_US: '/partner-with-us',
  CONTRIBUTE_MATERIALS: '/contribute-materials',
  NEWS_EVENTS: '/news-events',
  GALLERY: '/gallery',
  CONTACT: '/contact-us',
}; 